name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [file_uploaded]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # 移除cache: false配置，使用默认值
          
      - name: Process uploaded files
        if: github.event_name == 'repository_dispatch' && github.event.action == 'file_uploaded'
        run: |
          python upload.py "${{ github.event.client_payload.filename }}" "${{ github.event.client_payload.file_path }}" "${{ github.event.client_payload.timestamp }}"
          echo "Markdown文件内容:"
          cat src/upload.md
          echo "上传记录文件内容:"
          cat upload_records.json
          
      - name: Commit changes
        if: github.event_name == 'repository_dispatch' && github.event.action == 'file_uploaded'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add src/upload.md upload_records.json
          git commit -m "Update upload records for ${{ github.event.client_payload.filename }}" || echo "No changes to commit"
          git push
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    