name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    # 仅在工作流文件变更时触发，排除所有源文件路径
    paths:
      - '.github/workflows/deploy.yaml'  # 只监听工作流文件自身变更
  workflow_dispatch:  # 保留手动触发
  repository_dispatch:
    types: [file_uploaded]  # 保留文件更新工作流触发

# 并发控制以避免频繁部署
concurrency:
  group: ${{ github.ref }}-file-upload
  cancel-in-progress: true  # 取消旧的部署，只保留最新的

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    timeout-minutes: 10  # 设置作业超时时间
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Process uploaded files (batch)
        if: github.event_name == 'repository_dispatch' && github.event.action == 'file_uploaded'
        run: |
          BATCH_FILES=$(echo '${{ toJSON(github.event.client_payload.batch_files) }}' | jq -c .)
          echo "处理文件列表: $BATCH_FILES"
          FILE_COUNT=$(echo '${{ toJSON(github.event.client_payload.batch_files) }}' | jq '. | length')
          echo "文件数量: $FILE_COUNT"
          python upload.py "$BATCH_FILES" "${{ github.event.client_payload.batch_timestamp }}"
          
      - name: Commit changes
        if: github.event_name == 'repository_dispatch' && github.event.action == 'file_uploaded'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull origin main
          git add src/upload.md src/upload_records.json
          FILE_COUNT=$(echo '${{ toJSON(github.event.client_payload.batch_files) }}' | jq '. | length')
          git commit -m "Update upload records for batch of $FILE_COUNT files" || echo "No changes to commit"
          git push
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages with timeout
        id: deployment
        uses: actions/deploy-pages@v4
        timeout-minutes: 5  # 部署步骤单独设置超时
    