name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [file_uploaded]

# 关键配置：限制同一时间只有一个工作流实例运行
concurrency:
  group: ${{ github.ref }}-file-upload  # 基于分支的并发组
  cancel-in-progress: false  # 不取消正在运行的工作流，等待其完成

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，确保能拉取最新更改
          
      - name: 等待前序任务完成（额外保障）
        run: |
          echo "等待可能正在运行的工作流完成..."
          sleep 5  # 短暂延迟，给前序任务提交机会
          
      - name: 拉取最新代码（防止冲突）
        run: |
          git pull origin main
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Process uploaded files (batch)
        if: github.event_name == 'repository_dispatch' && github.event.action == 'file_uploaded'
        run: |
          # 将JSON数据转换为适当的格式传递给Python脚本
          BATCH_FILES=$(echo '${{ toJSON(github.event.client_payload.batch_files) }}' | jq -c .)
          echo "处理文件列表: $BATCH_FILES"
          # 使用jq获取文件数量
          FILE_COUNT=$(echo '${{ toJSON(github.event.client_payload.batch_files) }}' | jq '. | length')
          echo "文件数量: $FILE_COUNT"
          python upload.py "$BATCH_FILES" "${{ github.event.client_payload.batch_timestamp }}"
          echo "Markdown文件内容:"
          cat src/upload.md
          
      - name: Commit changes
        if: github.event_name == 'repository_dispatch' && github.event.action == 'file_uploaded'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull origin main  # 再次拉取最新代码，防止冲突
          git add src/upload.md src/upload_records.json
          # 使用jq获取文件数量并在提交信息中使用
          FILE_COUNT=$(echo '${{ toJSON(github.event.client_payload.batch_files) }}' | jq '. | length')
          git commit -m "Update upload records for batch of $FILE_COUNT files" || echo "No changes to commit"
          git push
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
