name: Deploy and Update Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [file_uploaded]  # 响应文件上传事件

jobs:
  process-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 如果需要其他依赖，可以在这里安装
          
      - name: Process uploaded files and update MD
        if: github.event_name == 'repository_dispatch' && github.event.action == 'file_uploaded'
        run: |
          python upload.py \
            "${{ github.event.client_payload.filename }}" \
            "${{ github.event.client_payload.file_path }}" \
            "${{ github.event.client_payload.timestamp }}"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
    