name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [file_uploaded] # 保持原有事件类型，无需新增

# 关键：确保同一时间只有一个工作流运行，避免并发覆盖
concurrency:
  group: ${{ github.ref }}-file-upload
  cancel-in-progress: false # 等待前一个工作流完成，不取消

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须有写入权限（提交MD和JSON文件）
      pages: write
      id-token: write
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
<<<<<<< HEAD
          fetch-depth: 0 # 拉取完整历史，避免Git提交冲突

      - name: 拉取最新代码（防止本地代码落后）
        run: git pull origin main
        continue-on-error: true # 若本地已是最新，忽略错误

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 与本地开发环境一致

      - name: 批量处理文件记录（调用Python脚本）
=======
          fetch-depth: 0  # 获取完整历史，确保能拉取最新更改
          
      - name: 等待前序任务完成（额外保障）
        run: |
          echo "等待可能正在运行的工作流完成..."
          sleep 5  # 短暂延迟，给前序任务提交机会
          
      - name: 拉取最新代码（防止冲突）
        run: |
          git pull origin main
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Process uploaded files
>>>>>>> f25bd37a499f6e56483283df922e917266bdfd07
        if: github.event_name == 'repository_dispatch' && github.event.action == 'file_uploaded'
        run: |
          # 关键：将GitHub事件中的batch_files（JSON）转成字符串，传递给Python
          BATCH_FILES_JSON='${{ toJSON(github.event.client_payload.batch_files) }}'
          BATCH_TIMESTAMP='${{ github.event.client_payload.batch_timestamp }}'
          
          # 打印参数调试（可选，便于排查问题）
          echo "批量文件JSON: $BATCH_FILES_JSON"
          echo "批量时间戳: $BATCH_TIMESTAMP"
          
          # 调用Python批量处理脚本（传递JSON字符串和时间戳）
          python upload.py "$BATCH_FILES_JSON" "$BATCH_TIMESTAMP"

      - name: 提交批量修改到Git
        if: github.event_name == 'repository_dispatch' && github.event.action == 'file_uploaded'
        run: |
          # 配置Git用户信息（必须，否则无法提交）
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # 检查是否有修改
          git status
          
          # 添加并提交（仅提交MD和JSON文件，避免意外提交）
          git add src/upload.md src/upload_records.json
          git commit -m "Batch update upload records (${{ len(github.event.client_payload.batch_files) }} files)" || echo "No changes to commit"
          
          # 推送修改（需确保workflow有写入权限）
          git push origin main

      - name: 部署到GitHub Pages（原有逻辑不变）
        uses: actions/configure-pages@v4
      - name: 上传Pages产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
<<<<<<< HEAD
      - name: 部署Pages
        uses: actions/deploy-pages@v4
=======
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
>>>>>>> f25bd37a499f6e56483283df922e917266bdfd07
